### ISSUE TITLE
About running the code

### ISSUE THREAD

**Issue by FastWind123** [abhisheksuran/Atari_DQN#1]
Hello! I wonder  what gpu do you use to train the dqn on? How many of them?
Have you successfully trained the network? If so, could you tell me how long does it take and how is the result?
Thank you very much!!

**Comment by abhisheksuran** [comment]
i used NVIDIA gtx 1050ti but this code(Atari one) is not memory efficient , memory overflows during training. I used 32 gb ram . For memory efficiency, you can look  at 
https://github.com/Huixxi/TensorFlow2.0-for-Deep-Reinforcement-Learning/blob/master/00_atari_dqn.py

**Comment by FastWind123** [comment]
OK！ Thank you very much!


| |
阎钰天
|
|
邮箱：yytmail123@163.com
|

签名由 网易邮箱大师 定制

On 05/04/2020 17:32, Abhishek Suran wrote:

i used NVIDIA gtx 1050ti but this code(Atari one) is not memory efficient , memory overflows during training. I used 32 gb ram . For memory efficiency, you can look at
https://github.com/Huixxi/TensorFlow2.0-for-Deep-Reinforcement-Learning/blob/master/00_atari_dqn.py

**Comment by abhisheksuran** [comment]
or you can use 32 gb ram :p  . It looks like tf 2 is eager by default thats why it need custom model and training atleast thats what i think . I also posted the question stackoverflow but no reply :p , u can look ques at https://stackoverflow.com/questions/58270765/how-to-minimize-ram-usage-for-training-atari-deep-q-learning-model

**Comment by FastWind123** [comment]
OK！ Thank you for your help!


| |
阎钰天
|
|
邮箱：yytmail123@163.com
|

签名由 网易邮箱大师 定制

On 05/04/2020 17:42, Abhishek Suran wrote:

or you can use 32 gb ram :p . It looks like tf 2 is eager by default thats why it need custom model and training atleast thats what i think . I also posted the question stackoverflow but no reply :p , u can look ques at https://stackoverflow.com/questions/58270765/how-to-minimize-ram-usage-for-training-atari-deep-q-learning-model
