### ISSUE TITLE
Not able to open  Reinforcement_Learning.ipynb file 

### ISSUE THREAD

**Issue by Anush-Onkar** [abhisheksuran/Atari_DQN#3]
Not able to open  Reinforcement_Learning.ipynb file, can you please fix this issue?

**Comment by abhisheksuran** [comment]
There is no such file with this name in this repo.

**Comment by Anush-Onkar** [comment]
Sorry, the file name is Reinforce_(PG).ipynb

**Comment by abhisheksuran** [comment]
You need to clone the repo. Many times, GitHub is not able to load Jupyter notebooks.
