### ISSUE TITLE
Wrong formatting of Reinforce_(PG).ipynb

### ISSUE THREAD

**Issue by Nadni** [abhisheksuran/Atari_DQN#7]
Hi, your code for "Reinforce_(PG).ipynb" seems to have some problems with the formatting so it does not show properly:

![immagine](https://user-images.githubusercontent.com/27709839/219973619-1babda84-b4ab-45bc-b69d-a9ba609cced3.png)

**Comment by abhisheksuran** [comment]
Hi, 
Kindly refer to "(https://github.com/abhisheksuran/Reinforcement_Learning/blob/master/Reinforce_(PG)_ReUploaded.ipynb)".
Thanks
